### ISSUE TITLE
PGV5 closes when importing data from PGV4

### ISSUE THREAD

**Issue by EBarbara** [pornganizer/PGV5#19]
Running on windows 10, I'm trying to import my PGV4 database to PGV5, but the software keeps closing a few seconds after starting the process.

**Comment by pornganizer** [comment]
i was able to import my v4 data, but I will go over the process again

**Comment by pornganizer** [comment]
Application: PGV5.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.IO.Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32, Boolean)
   at System.IO.StreamReader..ctor(System.String)
   at PGV5.V4Importer._importImages(Realms.Realm)
   at PGV5.V4Importer.<Import>b18_0(Realms.Realm)
   at Realms.Realm.Write(System.Action)
   at Realms.Realm+<>cDisplayClass48_0.<WriteAsync>b1()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Realms.Realm+<>cDisplayClass48_0+<<WriteAsync>gdoWorkAsync0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
AND:
Faulting application name: PGV5.exe, version: 0.0.2.0, time stamp: 0x5d27b123
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19358, time stamp: 0x5ccfa112
Exception code: 0xe0434352
Fault offset: 0x00000000000085bc
Faulting process id: 0x2b14
Faulting application start time: 0x01d538a730a94834
Faulting application path: D:\PGV4\PGV5.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 8f5eb49e-a49a-11e9-88e3-5435302aeeae
Faulting package full name: 
Faulting package-relative application ID:

**Comment by pornganizer** [comment]
fixed in 0.0.3
